name: realtime_ai
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.6.15
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=13.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.12.11
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.1
      - accelerate==1.8.1
      - aiofiles==24.1.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - argbind==0.3.9
      - asttokens==3.0.0
      - audioread==3.0.1
      - av==15.1.0
      - blinker==1.9.0
      - cachetools==6.2.0
      - certifi==2025.8.3
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cn2an==0.5.22
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - ctranslate2==4.6.0
      - cycler==0.12.1
      - cython==3.0.7
      - decorator==5.2.1
      - deepspeed==0.17.4
      - descript-audiotools==0.7.2
      - distance==0.1.3
      - docstring-parser==0.17.0
      - einops==0.8.1
      - executing==2.2.1
      - fastapi==0.115.13
      - faster-whisper==1.2.0
      - ffmpeg-python==0.2.0
      - ffmpy==0.6.0
      - filelock==3.13.1
      - fire==0.7.1
      - flask==3.1.2
      - flask-cors==6.0.1
      - flatbuffers==25.2.10
      - flatten-dict==0.4.2
      - fonttools==4.58.4
      - fsspec==2024.6.1
      - future==1.0.0
      - g2p-en==2.1.0
      - google-auth==2.41.1
      - google-auth-oauthlib==0.4.6
      - gradio==5.34.2
      - gradio-client==1.10.3
      - groovy==0.1.2
      - grpcio==1.75.1
      - h11==0.16.0
      - hf-xet==1.1.5
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.0
      - humanfriendly==10.0
      - idna==3.10
      - importlib-resources==6.5.2
      - indextts==2.0.0
      - inflect==7.5.0
      - ipython==9.6.0
      - ipython-pygments-lexers==1.1.1
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jieba==0.42.1
      - jinja2==3.1.4
      - joblib==1.5.1
      - json5==0.10.0
      - julius==0.2.7
      - keras==2.9.0
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - llvmlite==0.43.0
      - ltp==4.2.14
      - ltp-core==0.1.4
      - ltp-extension==0.1.13
      - markdown==3.9
      - markdown-it-py==3.0.0
      - markdown2==2.5.4
      - markupsafe==2.1.5
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - modelscope==1.27.0
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - munch==4.0.0
      - networkx==3.3
      - ninja==1.11.1.4
      - nltk==3.9.2
      - numba==0.60.0
      - numpy==1.26.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.580.65
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - oauthlib==3.3.1
      - ollama==0.5.1
      - omegaconf==2.3.0
      - onnxruntime==1.22.0
      - openai-whisper==20240930
      - opencv-python==4.9.0.80
      - orjson==3.10.18
      - packaging==25.0
      - pandas==2.3.2
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.8
      - pooch==1.8.2
      - proces==0.1.7
      - prompt-toolkit==3.0.52
      - protobuf==3.19.6
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyaudio==0.2.14
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pyloudnorm==0.1.1
      - pynini==2.1.6
      - pyparsing==3.2.3
      - pyphen==0.17.2
      - pystoi==0.4.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - randomname==0.2.1
      - regex==2024.11.6
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rich==14.0.0
      - rsa==4.9.1
      - ruff==0.12.0
      - safehttpx==0.1.6
      - safetensors==0.5.2
      - scikit-learn==1.7.0
      - scipy==1.16.0
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - setuptools-rust==1.11.1
      - shellingham==1.5.4
      - silero-vad==5.1.2
      - six==1.17.0
      - sniffio==1.3.1
      - sounddevice==0.5.2
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - stack-data==0.6.3
      - starlette==0.46.2
      - sympy==1.13.3
      - tensorboard==2.9.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - termcolor==3.1.0
      - textstat==0.7.10
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.21.0
      - tomlkit==0.13.3
      - torch==2.8.0
      - torch-stoi==0.2.3
      - torchaudio==2.8.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.52.1
      - triton==3.4.0
      - typeguard==4.4.4
      - typer==0.16.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.34.3
      - wcwidth==0.2.14
      - webrtc-noise-gain==1.2.5
      - webrtcvad==2.0.10
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wetextprocessing==1.0.4.1
      - whisper==1.1.10
